### ISSUE TITLE
Blacklist debuff-group

### ISSUE THREAD

**Issue by holypalaswe** [bkader/Grid2-WoTLK#10]
Yo, I use this addon on retail/classic TBC and I am able to make debuff-groups that show all debuffs on the target, except specific ones I blacklist. I can't seem to find this functionality on this wotlk version, and sadly I have very limited knowledge of lua and addons in general. If this is something you could look at I'd be very grateful.

Or just be able to see all debuffs on the raidframes without a blacklist function will be enough, using icons indicator.

![image](https://user-images.githubusercontent.com/29150498/163849209-9858bdca-0728-4b55-9365-b78cb2921842.png)

**Comment by bkader** [comment]
Hello @holypalaswe .. You were probably using another version on retail and not the one I backported. I will see what I can do.

**Comment by bkader** [comment]
I am afraid I no longer have the time nor the energy to add this feature, so I am closing this issue.
My sincere apologies.
