### ISSUE TITLE
Combat Status

### ISSUE THREAD

**Issue by Hantzaha** [bkader/Grid2-WoTLK#11]
1x Grid2Options-r736\modules\statuses\StatusCombat.lua:23: attempt to call method 'UpdateAllUnits' (a nil value)
(tail call): ?:
<in C code>: ?
<string>:"safecall Dispatcher[2]":9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?:
AceConfigDialog-3.0-50:797: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:612>
(tail call): ?:
<in C code>: ?
<string>:"safecall Dispatcher[3]":9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?:
AceGUI-3.0-33 (Ace3):314: in function `Fire'
...ns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:68: in function <...ns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>:

  ---

**Comment by bkader** [comment]
A description of how this happened would be nice and helpful. Pasting the error doesn't help I am afraid.

**Comment by Hantzaha** [comment]
I was testing, why the Combat Status wasn't showing in my status icon.  

![WoWScrnShot_042322_172151](https://user-images.githubusercontent.com/92329804/164948237-6674eddb-9246-44ea-980a-c940b29b4654.jpg)

I discover  the status  "Combat:mine"works well.   
But the General "Combat" Status don't .

![WoWScrnShot_042322_165533](https://user-images.githubusercontent.com/92329804/164948287-03d3ad75-5586-45a0-9d94-865013bcff35.jpg)


When I tried the option  "Use Empty Icon"  just to see what happen 
is when the error showed.

![WoWScrnShot_042322_165618](https://user-images.githubusercontent.com/92329804/164948297-f4ca573a-3ddf-401e-88d5-b3aa2eab2699.jpg)
