### ISSUE TITLE
Player Mind Controlled by Lady Deathwhispers looks faded

### ISSUE THREAD

**Issue by Hantzaha** [bkader/Grid2-WoTLK#12]
When
 Lady Deathwhispers uses “Dominate Mind” the targeted player looks “faded". 

-The Alpha Change, like is far away

-Or the new red color (Hostile) is applied on top all layers and make the unit  
looks “faded”  maybe..

![dominated_mind_042922_203628](https://user-images.githubusercontent.com/92329804/166115882-76b6d7b7-e14f-4ade-8196-4e168a58ca4e.jpg)

![dominated_mind_042922_203638](https://user-images.githubusercontent.com/92329804/166115892-62c309b2-eb50-488d-b5f1-de18bd3f3cb4.jpg)

![dominated_mind_042922_203720](https://user-images.githubusercontent.com/92329804/166115904-94079810-e114-407a-bc9f-cf76751dc049.jpg)

**Comment by Hantzaha** [comment]
OR  maybe is the "Cyclone" effect  ???

**Comment by bkader** [comment]
Sorry for the late reply @Hantzaha .. Wether it is MC or Cyclone, I believe both put the player out of range because of how the spell works, it is not a bug as far as I know.
