### ISSUE TITLE
Suggestion  to improve direction status (arrows pointing to each raid member)

### ISSUE THREAD

**Issue by Hantzaha** [bkader/Grid2-WoTLK#13]
I found an add-on that seems to make this function (and works in grid2)

https://www.curseforge.com/wow/addons/direction-arrow

I think uses or is based in this library  

https://www.curseforge.com/wow/addons/astrolabe

And It works (with some game restrictions) 

![arrow_043022_143240](https://user-images.githubusercontent.com/92329804/166154896-5f83a402-1643-48ad-b6c1-7b09f6fd5d49.jpg)

Also works with death people

![arrow1_043022_143444](https://user-images.githubusercontent.com/92329804/166154480-c44d8749-fb79-481a-a406-e2bb6b7c5274.jpg)

![arrow2_043022_143446](https://user-images.githubusercontent.com/92329804/166154510-74f3eb08-5faa-43f3-bdd1-168a9df7722d.jpg)

Even  in  ghost mode

![arrow3_043022_154030](https://user-images.githubusercontent.com/92329804/166154536-a8402fd1-4ab1-40ce-955c-0708f3cd81e6.jpg)

**Comment by bkader** [comment]
@Hantzaha I like what the addon does that but I cannot change the default Grid2 direction I am afraid, not everyone would agree to such change. However, Grid2's direction arrow was buggy, the next push will fix i and closes this issue automatically.
