### ISSUE TITLE
hide grid2 while alone

### ISSUE THREAD

**Issue by abel8909** [bkader/Grid2-WoTLK#2]
I want it to show grid2 when I am in a group or raid, but when I am only seeing a small box 
I just downloaded the addon today

https://user-images.githubusercontent.com/89325544/132992642-34c3399a-cb4e-4cf2-a864-18dc000b7ad6.mp4

**Comment by bkader** [comment]
Hello @abel8909, I don't know why you're having this problem but as you can tell from the video, it doesn't happen at all. It may be related to wrong installation or some conflict, I don't know what addons you have enabled.

https://user-images.githubusercontent.com/4732702/132993668-380b6e84-7767-49f8-86a1-6555e152d325.mp4

**Comment by abel8909** [comment]
It is strange, I did the test disabling all the addons except bugsack and grid2, I even deleted the WTF folder and cache, I also did the relog and / reload test and the problem remains the same

**Comment by abel8909** [comment]
wait, I just noticed your video well, the little square is clearly visible
![aaaa](https://user-images.githubusercontent.com/89325544/132994552-d9237ce5-31e6-4227-a861-08540d55b397.png)

**Comment by bkader** [comment]
There is in option in General settings that allows you to show Grid frame only when you are in a group/raid.
