### ISSUE TITLE
mana bar / raid debuff / range

### ISSUE THREAD

**Issue by Irsont** [bkader/Grid2-WoTLK#6]
why part of the manabar is displayed for those who have no mana, how to fix it?
https://i.ibb.co/wcNKQQZ/image.png

how to display raid debuff border by state color?
https://i.ibb.co/xYnMgHB/image.png

and why alpha does not work when the player in the vehicle or ghost?
https://i.ibb.co/S7GVdG3/image.png

**Comment by bkader** [comment]
> why part of the manabar is displayed for those who have no mana, how to fix it?

This indicator/status is only displayed for players that use mana, please check your settings.

> how to display raid debuff border by state color?

By default, Raid Debuffs should have a purple color, you can create up to 10 raid debuffs **groups** (_emphasis on groups_), after creating your group and setting the its color, your can go to the raid debuffs tab (_on which you see the list of raids, bosses and debuffs_) then add the debuffs you want to the group you created on the right side of the panel. Once this is done, you simply go to the indicator on which you are displaying raid debuffs, scroll down and you will find the **Border** settings, tick `Use Status Color`. That's all. Of course, don't forget to adjust the border size as 0 simply means no borders are visible.

> and why alpha does not work when the player in the vehicle or ghost?

The alpha indicator uses what the API or statuses provide (_using provided percentage depending on the status_). For example, dead players that released are considered out of range, the same goes for disconnected and far away players. These are default statuses. If any other used status provides a percentage, it will be used to determine the alpha. If players are in vehicles for example and cannot be targeted, they are considered _not in rage_ as well... etc. I will have to dig more to be sure that what I mentioned above is correct and you will probably need to play with the settings until you get the result you want.

**Comment by Irsont** [comment]
everything is fine with the settings, but I don’t know what is the reason, here is the 
[grid2 profile.txt](https://github.com/bkader/Grid2-WoTLK/files/8147158/grid2.profile.txt)

is it possible to add a status color checkbox for raid debuffs?

**Comment by bkader** [comment]
I will check the profile asap.
As for the status color checkbox, please go on the indicator on which you are displaying raid debuffs, scroll all the way down on the 3rd panel where you can customize the border's color, there is a checkbox to use the status color.

**Comment by Irsont** [comment]
> I will check the profile asap. 

ok, thanks

> As for the status color checkbox, please go on the indicator on which you are displaying raid debuffs, scroll all the way down on the 3rd panel where you can customize the border's color, there is a checkbox to use the status color. 

i know, but it still repaints the border in the color specified in the raid debuffs, look in the profile, thanks

**Comment by bkader** [comment]
I have tested your profile @Irsont and here are the problems explained in short videos:

### Icon Border:

https://user-images.githubusercontent.com/4732702/155881505-b3720d88-1f1a-45b0-845a-87922c27fb07.mp4

### Mana Bar Background

https://user-images.githubusercontent.com/4732702/155881581-7a0a0ebf-3105-44e0-aedc-41f00ff64793.mp4

### Range Detection

https://user-images.githubusercontent.com/4732702/155881593-74559faf-3fcb-4082-9e9b-7d96152ab552.mp4

I hope this answers all your questions.
