### ISSUE TITLE
offline bug

### ISSUE THREAD

**Issue by mzxwar** [bkader/Grid2-WoTLK#8]
hi~ I found a bug,  its about not triggering the icon after someone goes offline, could u fix it? thx~

**Comment by bkader** [comment]
Hi @mzxwar . Can you explain the issue in more details please? It is a bit vague. What icon, what status .. etc

**Comment by mzxwar** [comment]
>UMM... When someone on the party goes offline, it should display an "offline icon" or "offline" text on grid2, but it doesnt working,  i have to input /RL the icon and text will be display. sorry about my bad English. XD
